### ISSUE TITLE
Disable debug logging

### ISSUE THREAD

**Issue by cschol** [hdavid/VCVRack-Holon.ist#1]
For integration in the Plugin Manager you should disable/remove the debug logging:

```
Ports::start()
Ports: starting OSC server
Ports: starting mDNS server
[...]
Ports::stop()
Ports: stop Osc Server (shouldRun = false)
Ports: stop mDNS Server (shouldRun = false)
Ports: terminate OSC Server
Ports: mDNS server terminated
```

**Comment by hdavid** [comment]
Hi thanks ! 
This is done in  commit : 22e390ca9440e45ec0d01f0d32d06f197006c4a4

Is is allowed to use Rack logging function 
https://github.com/VCVRack/Rack/blob/v0.6/include/util/common.hpp#L214
or there should be no logging at all in plugins ?

regards,

henri

**Comment by cschol** [comment]
You can use it during development obviously, but note, that they are **not compiled out during a release build**. Therefore, you should remove them before submitting to the Plugin Manager.

**Comment by hdavid** [comment]
i okay clear ! thank you !
