### ISSUE TITLE
Gaps - LEDs won't go back to off + clock tag

### ISSUE THREAD

**Issue by jsmonzani** [hdavid/VCVRack-Holon.ist#10]
Testing the current version with Rack 1.1 on Windows, Gaps LEDs are on when active but won't turn back to off when they're inactive.

Another request: please add "clock" to your keywords. I use Gaps as a clock divider (and I think it's its purpose) and searching Clock divider in the new plugin system in Rack won't show it.

Thank you!

**Comment by hdavid** [comment]
Hi,

indeed, thanks for reporting this one. i will have a look in the coming days and release a fix for this.

cheers,

Henri

**Comment by hdavid** [comment]
fixed. will be released in plugin version 1.0.2. 
note that the plugin is found while searching for clock (it has the tag "Clock Modulator")
