### ISSUE TITLE
a feature request for lazy susan

### ISSUE THREAD

**Issue by rsmus7** [hdavid/VCVRack-Holon.ist#11]
I really like your modules and use lazy susan really often in my patches,
so here my question:
would it be possible to have a cv input (best with attennuverter knob) to controll the "cv att" knob?
that would be cool.

mercy beaucoup for the holonic modules

**Comment by hdavid** [comment]
hi, 
That seems a bit niche use case (or maybe i missed smth ?) and i guess you could emulate this with a quad VCA quite easily. i am wrong ?

**Comment by rsmus7** [comment]
well a vca could do it, but it is not really that handy for it, 
as it is now I use stoermelder µmap for the "misssing" cv controll of the "cv att" knob
but a dedicated input would be nice.

**Comment by hdavid** [comment]
for now i would prefer to keep it simple, adding one more input + att would clutter the ui. :/
