### ISSUE TITLE
Gaps in trigger mode fires to all outputs on first clock

### ISSUE THREAD

**Issue by Petervos2018** [hdavid/VCVRack-Holon.ist#12]
With Gaps in trigger mode it fires off a trigger to all the outputs on the first clock...
That can't be right ?
The more I'm testing this the less I understand how this works.
What does "as is" do ?

> EDIT : I think I figured it out , say you have an 8 out it will stay high for 4 clocks and then low for four clocks in gate mode you get a long 4 clocks high and a long 4 clocks low like this
 HIGH____HIGH____
 In as is mode during the high the clock triggers the gate/trigger and it looks like
 TTTT____TTTT____ so during the high gate the clock is coming out of the output.
 Am I right ?  

When I connect something to an output named "3" I expect it to fire off a trigger/gate every 3rd clock so:
xxTxxTxxT... etc
This does not happen with Gaps.
It does this :
xTxxTxxTxxT... in gate mode
TxxTxxTxxT..... in trigger mode
xTTxTTxTT...... in as is mode <= this mode then start to fire of all sorts of strange gates to groups of outputs. Or maybe it just looks that way because the gates stay high.

Here is a simple vcv that shows this phenomenon 

I think removing the trigger from the first clock will solve all/most of my problems. <-- naah it does not.
[Gaps Divider 22092019.zip](https://github.com/hdavid/VCVRack-Holon.ist/files/3640022/Gaps.Divider.22092019.zip)

Greetings Peter.

EDIT : in case you think I sounded like an a$$hole in the above message, it's because I was/am still struggling with dividers not doing what I want. Here is my latest attempt : 

![ClockDividers-29092019](https://user-images.githubusercontent.com/46076474/65867445-b8f1a100-e376-11e9-81b6-83ab46e869a3.png)

Only the three on the top left do what I want.
And a zip to test it/them all...

[ClockDividers - 29092019.zip](https://github.com/hdavid/VCVRack-Holon.ist/files/3670106/ClockDividers.-.29092019.zip)

**Comment by hdavid** [comment]
Hi  Peter,

Thanks a lot for spotting this and taking the time to write a detailed bug report, i have quite busy with other projects and kind of over looked this.

You are totally right the behaviour was wrong, i fixed and will submit the fix to Andrew.
The Trigger mode just output a standard trigger.
The Gate mode keeps the output high until the next clock
The "as is" mode keeps the output high as long as the input clock is also high. (but indeed it was buggy).

cheers,

henri

**Comment by Petervos2018** [comment]
So I was not a complete a$$hole then... : ;)
Thanks for taken the time to look at and fix some of my "problems".

Greetings Peter.

**Comment by hdavid** [comment]
hi again, 

Actually i had a deeper look at how other modules work, and while mathematically a clock divider should fire on the  Nth clock input, granted, musically it might be a different thing and everything might then sound off beat.
So i looked for a reference and i hope you would agree that this could be considered a reference : http://www.doepfer.de/a1602.htm

i will update the module accordingly :)

while at it i added a new mode: http://holon.ist/vcv/
Four modes are available:
Gate: the output stays high until the next clock input trigger
Gate2: the output stays high half of the time (50% duty cycle)
Trig: the output outputs the standard trigger upon input trigger
As is: the output remains high as long as the clock input is high

**Comment by Petervos2018** [comment]
You lost me at "hi again",  ;)
Yes I know there are two camps of dividers (musical and theoretical or something like that), the ones that fire all divisions on the first trigger (this means they always start on the second step when something is connected to them, that I hate with all my strength) and those that trigger only on the Nth step (these are the ones I love so much).
Let's see what the update brings and if I can start using/loving the Gaps again....

Greetings Peter.

EDIT : BTW trigger is the one I used to use until I found out it triggers all outputs on the first trigger (option 3 of 4 modes) option 1 and 2 probably also trigger on the first step and so does "as is" so this probably will not be the module for me :( But maybe I'm wrong...

BTW how does gate 2 know how long to stay high after the first trigger ?

**Comment by hdavid** [comment]
Well. As it's a question of love.... i would not want to disappoint you ! 
Gaps will support both modes. musical and mathematical. 
ui is now cramped up a little. but that's still usable :)
![image](https://user-images.githubusercontent.com/566554/73141560-b9304d80-4085-11ea-8da7-a2a8d42e22aa.png)

http://holon.ist/vcv/
Additionally, Gaps can behave in two ways:
Musical: triggers on the first clock
Mathematical: if the divide ratio is say 3, it will trigger on the 3rd clock

by the way, trigger and gate modes should go high on the same beats actually. but it might have been buggy.

**Comment by Petervos2018** [comment]
Well in case of love,
if I don't love Gaps I will still love you, 
Thanks for all your hard work,

Greets Peter.

BTW at 200% the GUI looks very decent ;)

**Comment by Petervos2018** [comment]
We must be cursed, I can see the update1.0.2 -> 1.0.3 in rack but there is no way rack is updating the module.
Maybe ask Andrew what is going on, W7 and W10 are updating all but your modules :(

Greets Peter.

**Comment by hdavid** [comment]
maybe delete the folder Holonic Systems Free under MyDocuments/Rack/plugins-v1 and let it reinstall them ?

**Comment by hdavid** [comment]
hum indeed smth is not right. i will check with andrew.

**Comment by Petervos2018** [comment]
YES it(the module and the download) works and "mathematical" "as-is" is my new favourite , 
Thank you, I love it/you 👍 

Greetings Peter.

**Comment by hdavid** [comment]
i'm happy that you're in love again :)
