### ISSUE TITLE
Pantry not recording Gates properly

### ISSUE THREAD

**Issue by marcusbrutulus** [hdavid/VCVRack-Holon.ist#13]
If I send clock gate it records a solid on gate for all steps. If I send other gates it records nothing at all. CV recording works fine. Consequently I can't record or use any gate information.

**Comment by hdavid** [comment]
hi, 
both gate and CV channels record what they receive at the input and reproduce it for the duration of the step. so if you want to have a gate off, you need somehow to record a gate off information at some point. you could use double clock speed for the input for instance.

as for the missed trigs, it records (samples) the Gate (and CV) input exactly on the clock input. so it might be that in your patch smth introducs a latency and makes it miss the trig.

cheers,

henri
