### ISSUE TITLE
trigger not outputting

### ISSUE THREAD

**Issue by jt-berg-whitt** [hdavid/VCVRack-Holon.ist#14]
I was following Omri Cohen on youtube and studying fun ways to auto-gen melodies and what not, but for some reason my lazy susan module isn't outputting anything at all to the trigger in AD Attack like his does...I'm new to this so I might have done something wrong, but I don't think so...I figured I would ask the creator but I also am not sure if this is a silly question not worthy of being posted here...

https://imgur.com/s68CXv1

**Comment by hdavid** [comment]
it is because lazy susan is outputting a (very short) trigger, and not a gate.
use an env generator that has a release parameter and it should work just fine as in this example below:
https://imgur.com/a/T2sMQQ5
