### ISSUE TITLE
Plugin update stalls

### ISSUE THREAD

**Issue by ajbmorris** [hdavid/VCVRack-Holon.ist#16]
Rack is notifying that I have an update, but on clicking update for Holonic nothing happens.
Tried removing plugin folder from user/docs on win10 and also resetting status with the button on the plugins page/website - still happens.

**Comment by hdavid** [comment]
Hi, indeed this a known issue. We are looking at it with the vcv team.
Regards,
Henri

**Comment by ajbmorris** [comment]
Thanks Henri - that's great; looking forward to seeing the updates.

**Comment by hdavid** [comment]
this should be fixed now. thanks to @AndrewBelt :)
