### ISSUE TITLE
Issues with saving a patch when using pantry, does not save what was recorded

### ISSUE THREAD

**Issue by gentlewatcher** [hdavid/VCVRack-Holon.ist#17]
I understand not saving the recording to a file but please make it so the recording is stored in the modules data in a way that it could be saved as part of the patch, or just let us save it to a file this module is very useful for quick midi prototyping of beats.

**Comment by hdavid** [comment]
Hello, the dev of this plugin suite is kind of on hold for now.  but feel free to contribue/fork :)
