### ISSUE TITLE
Polyphonic input and output for Pantry

### ISSUE THREAD

**Issue by ohechtl** [hdavid/VCVRack-Holon.ist#18]
Hey! I'm trying to find a sequencer in VCV Rack which can record and output polyphonic CV and gate. As you can see in the below picture, I've managed to do it for 6 channels, but it'd quickly get horrible for 16 channels.

I'm suggesting that Pantry could handle poly cables, which would solve my problem.

What do you think about this idea? Could this be a good addition to this module?

Thanks!

![image](https://user-images.githubusercontent.com/42605027/117313039-d4435d00-ae85-11eb-83f1-0b0a92ee9368.png)

**Comment by hdavid** [comment]
Hi Oliver,

Thanks for the suggestion!

I had a quick look at it and managed to put something together for Pantry and Lazy Susan and put the code in this branch:
https://github.com/hdavid/VCVRack-Holon.ist/tree/polyphonic

If you dont want to wait for the next release, and given you are a developer, you should be able to compile the plugin from source and give it a try. Compiling plugins is easier than it seems ! 
https://vcvrack.com/manual/PluginDevelopmentTutorial#Prerequisites
https://vcvrack.com/manual/Building#setting-up-your-development-environment

Cheers

**Comment by ohechtl** [comment]
Hi! 

Thank you for the quick reply and code, I'll try it out and get back to you! :)

**Comment by ohechtl** [comment]
This is awesome, thank you! 

This opened so many jamming possibilities for me :)

This is very useful for recording sequences from KeyStep, but with the additional modular abilities :)
