### ISSUE TITLE
Gaps internal clock

### ISSUE THREAD

**Issue by XtremeSounds** [hdavid/VCVRack-Holon.ist#22]
Hi this clock divider would be a great size if it just had its own internal clock and rate settings

**Comment by hdavid** [comment]
That's true it would be nice, but at the same time it is nice to keep each device focused on one function. 

Adding an internal clock would mean to add a clock output (currently all outputs are divided), a knob to adjust the clock rate, a display to display the current clock rate, then would come the request for swing support, and a never ending range of great ideas. Also in many cases users will want to use an external clock (coming from ableton link or an external audio clock).

For these reasons i think it makes more sense to not include this functionality and keep the module smaller and task focuses.

i hope this makes sense.
