### ISSUE TITLE
successful build for Rack v1

### ISSUE THREAD

**Issue by davephillips** [hdavid/VCVRack-Holon.ist#3]
Fedora 23 Linux
Rack v1.dev.500e5e0

Just a note to let you know I've built and installed your plugin for the current Rack v1 repo. The modules no longer crash the browser, but I haven't tested them yet. I'll report back when I've given them a spin over the weekend.

Nice work. :)

**Comment by hdavid** [comment]
thanks for the report ! :)

let us know how it works and if you find bugs.

**Comment by hdavid** [comment]
how did the testing go ? i pushed a couple of update just a few moments ago.

**Comment by davephillips** [comment]
Sorry for the delay, we've had some very bad days here recently. I'll get to the tests today or tomorrow, will post results asap.

**Comment by hdavid** [comment]
sorry to hear. take it easy... no rush.

**Comment by hdavid** [comment]
updated source in branch v1 to work with last API. 
synced changed from trunk
