### ISSUE TITLE
LazySusan Quantizer issue. 

### ISSUE THREAD

**Issue by veryfungi** [hdavid/VCVRack-Holon.ist#5]
I may have found an issue. I want the notes G4 A4 B4 D5 E5. I set the correct voltage range and deselected C, but am still seeing C5 show up.

![trouble-08](https://user-images.githubusercontent.com/39309125/56588924-e9eccf00-65a9-11e9-95ae-a3d32577c6e1.jpg)

**Comment by hdavid** [comment]
indeed there is a bug there. will have a look.
thanks for reporting !

**Comment by hdavid** [comment]
will be released in the next version (0.6.5).

**Comment by veryfungi** [comment]
This is great, thanks I can't wait to try it!

**Comment by hdavid** [comment]
hi,
it's released!
