### ISSUE TITLE
Questions about Lazy Susan

### ISSUE THREAD

**Issue by Petervos2018** [hdavid/VCVRack-Holon.ist#6]
Hi Henri,

Transpose will only transpose to a selected note, if I have a scale with only C and G  when I transpose a C it will only go to a G there is no way to transpose f.i. 1 or 2 semitones.

Transposing and CV input from C4 backwards (negative volts) will go to B3 then B2 B1 etc. nothing in between no matter what notes are chosen in the scale.

Is this by design or are these bugs ?

Greetings Peter.

I attached a simple vcv (in a zip) file for me/you to show/test what I mean.
[LazySusanTest-02052019.zip](https://github.com/hdavid/VCVRack-Holon.ist/files/3139798/LazySusanTest-02052019.zip)

**Comment by hdavid** [comment]
indeed smth is off around there. transpose should just be added before quantisation if i am not wrong.
we are prepering for superbooth next week (come visit us if you are around), so i will have a look after superbooth. thanks for reporting !

**Comment by hdavid** [comment]
Hi,
i managed to fix the bug, thanks for reporting it!
it will be released with version 0.6.6 of the plugins (submitting to andrew now). you can of course build from source in the meantime if you wish.
