### ISSUE TITLE
Bug in Dumbwaiter

### ISSUE THREAD

**Issue by MaZe6K** [hdavid/VCVRack-Holon.ist#7]
Hi there!
First of all thank you for these amazing modules! Until now I have only used the Dumbwaiter and I love it!
I think I found a bug though: If the start position is moved to a point where the sequence overlaps to the first steps it goes kind of wild. For example: I have a sequence set to a length of 3 steps and play around with the start position, it's fine up until I reach steps 6-7-8, but then if I set the start position to 7 it plays 1-5-6-7-8, and if I set it to 8 it just plays 8-1. Of course I would expect it to play 7-8-1 and 8-1-2.

**Comment by hdavid** [comment]
Hi,

Thanks for the bug report ! 

Indeed smth was wrong in there. After a bit head scratching and hair pulling, i found the bug it is now fixed : https://github.com/hdavid/VCVRack-Holon.ist/commit/4faa439142008ba4661bd5340726b1b933bf3f67#diff-9267cc2999b21e9ba244331b310cbe83L189

i will submit the bug fix to Andrew and it should be available in version 0.6.7 of the plugins in a few days.

thanks again for reporting it.

henri

**Comment by MaZe6K** [comment]
That's very cool! Thank you!

There's one more thing where I don't know if it's a bug: The "address" input on the top doesn't seem to work, I expected it to receive voltages from 0-8 (or 0-10) and jump to the corresponding step on the next gate, but no matter what voltage I put into it, it always stays on step 1 when connected.

And while I'm here already: Do you have everything ready for 1.0? I'm eagerly awaiting the release, which should happen during the next few days, and I have big plans for it which involve Dumbwaiter being controlled with a MIDI-controller :) I read on the forum that API and ABI are stable so plugins can now be compiled for the final 1.0 and can already be downloaded in the plugin manager to use with the current pre-release.

**Comment by hdavid** [comment]
hi,

the address should work. continuously when not clock signal is plugged in and on clock input if a clock jack is plugged in.
i tested it in the (to be released) last version of the plugins and it works fine and as expected. make sure the attenuator on the right of the jack is turned on.


v1.0 : yeap, i just committed the fixes as the API is now set in stone for 1.0 :)
https://github.com/hdavid/VCVRack-Holon.ist/commits/v1
you can compile it from source it should work.

**Comment by MaZe6K** [comment]
nice! thank you!
